[workspace]
members = [
    "sudachi",
    "sudachi-cli",
    "sudachi-fuzz",
    "plugin/input_text/*",
    "plugin/oov/*",
    "plugin/path_rewrite/*",
    "python",
    "timeperf-original",
    "timeperf-packed",
    "timeperf-packed2",
]

default-members = [
    "sudachi",
    "sudachi-cli"
]